---
- name: setup web server
  hosts: localhost
  become: true
  become_user: root

# install multiple roles from command line
# Use: packer build -var 'roles=role1,role2,role3' template.json
  vars:
    a_roles: web
    dest_folder: /tmp

  tasks:
  - name: create list of incoming roles
    set_fact:
      ansible_roles: "{{ a_roles.split(',') }}"
      
  - name: install roles
    include_role:
      name: "{{ item }}"
    vars:
      dest_dir: "{{ dest_folder }}"
    with_items: "{{ ansible_roles }}"
