---

- name: Update and upgrade apt packages
  become: 'True'
  apt:
    upgrade: yes
    update_cache: yes

# - name: Installation
#   apt:
#     name: "{{ packages }}"
#     update_cache: yes
#     state: latest
#   vars:
#     packages:
#       - python3-selinux
#       - selinux-policy

# - name: Install SELinux python3 tools
#   package:
#     name:
#       - libselinux-python3
#       - policycoreutils-python3
#     state: present

- name: Disable IPv6
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - { name: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
    - { name: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
    - { name: 'net.ipv6.conf.lo.disable_ipv6', value: '1' }

- name: Limit "open files" All Users/Processes in /etc/security/limits.conf
  pam_limits:
    domain: '*'
    limit_type: "{{ limit.name }}"
    limit_item: nofile
    value: "{{ limit.value }}"
  with_items:
    - { name: 'hard', value: '65535' }
    - { name: 'soft', value: '65535' }
  loop_control:
    loop_var: limit

- name: SSH Security
  lineinfile:
    state: present
    path: /etc/ssh/sshd_config
    regexp: "{{ ssh.name }}"
    line: "{{ ssh.value }}"
  with_items:
    - { name: '^#?PermitRootLogin', value: 'PermitRootLogin no' }
    - { name: '^#?AllowUsers', value: 'AllowUsers ubuntu' }
    - { name: '^#?AllowAgentForwarding', value: 'AllowAgentForwarding yes' }
  loop_control:
    loop_var: ssh

# - name: Enable SELinux
#   selinux:
#     policy: targeted
#     state: enforcing

- name: "Ensure SSH Port Open on Firewall"
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
