---

- name: Update and upgrade apt packages
  become: 'True'
  apt:
    upgrade: yes
    update_cache: yes

- name: Installation
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
      - apache2
      - apache2-utils
      - libapache2-mod-wsgi-py3
      - chrony
      - telnet
      - mtr
      - tree
      - git
      - python3-pip

- name: Create home
  file:
    path: "{{ apache_dir }}"
    state: directory

- name: get Git Repo Code
  git:
    repo: "{{ git_repo }}"
    dest: "{{ repo_folder }}"
    update: yes

- name: install Python requirements (using python3)
  pip:
    chdir: "{{ repo_folder }}"
    requirements: requirements.txt

- name: ensure app runs as python3
  lineinfile:
    path: "{{ repo_folder }}/tiny_app.py"
    line: '#!/usr/bin/env python3'
    insertbefore: BOF

- name: copy python file to web directory
  copy:
     src: "{{ repo_folder }}/tiny_app.py"
     dest: "{{ apache_dir }}"
  delegate_to: localhost

- name: add wsgi file
  template:
    src: tiny_app.wsgi.j2
    dest: "{{ apache_dir }}/tiny_app.wsgi"
  delegate_to: localhost

- name: add virtualhost
  template:
    src: tiny_app.conf.j2
    dest: "{{ apache_config }}/tiny_app.conf"
  delegate_to: localhost

- name: Web Server config directory - apache2.conf
  shell: 'sudo sed -i -e "s/^<Directory \\/var\\/www.*$/<Directory \\/var\\/www\\/python\\/>/" /etc/apache2/apache2.conf'

- name: enable virtual site
  command: a2ensite tiny_app.conf

- name: disable default site
  command: a2dissite 000-default.conf

- name: enable mod-wsgi
  command: a2enmod wsgi

- name: Change Apache port - ports.conf
  shell: "sudo sed -i -e 's/^Listen.*$/Listen {{ apache_port }}/' /etc/apache2/ports.conf"
  when: change_port | bool

- name: "Ensure Apache Port Open on Firewall"
  ufw:
    rule: allow
    port: "{{ apache_port }}"
    proto: tcp

- name: Enable override redirects - apache2.conf
  shell: 'sed -i -e "/^<Directory \\/var\\/www\\/python\\/>.*/{n;n;s/None.*$/All/;}" /etc/apache2/apache2.conf'
  when: override_redirects | bool

- name: Ensure directories are 0750
  command: find {{ www_dir }} -type d -exec chmod -c 0755 {} \;

- name: Ensure files are 0640
  command: find {{ www_dir }} -type f -exec chmod -c 0644 {} \;

- name: Ownership of www content files
  file:
    path: "{{ www_dir }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  notify: restart apache2

- name: enable chrony - NTP
  systemd:
    name: chronyd
    state: started
    enabled: yes
